### ISSUE TITLE
Can't get translations to work

### ISSUE THREAD

**Issue by rhaamo** [jwag956/flask-security#108]
Trying here where I might have more chance with an undead fork.

I'm using flask_babelex in my app and the app translation itself works fine, but the flask-security part stays in english.

```python
def create_app():
...
    babel = Babel(app)  # noqa: F841
...
    security = Security(  # noqa: F841
        app, user_datastore, register_form=ExtendedRegisterForm, confirm_register_form=ExtendedRegisterForm
    )
...
    @babel.localeselector
    def get_locale():
        # if a user is logged in, use the locale from the user settings
        identity = getattr(g, "identity", None)
        if identity is not None and identity.id:
            return identity.user.locale
        # otherwise try to guess the language from the user accept
        # header the browser transmits.  We support fr/en in this
        # example.  The best match wins.
        print(f"Best locale choosed: {request.accept_languages.best_match(AVAILABLE_LOCALES)}")
        return request.accept_languages.best_match(AVAILABLE_LOCALES)

    @babel.timezoneselector
    def get_timezone():
        identity = getattr(g, "identity", None)
        if identity is not None and identity.id:
            return identity.user.timezone
```

My `get_locale` returns "fr" as my browser have been set in french, but flask-security form labels and error messages stays in english.

An example is my register form, which have an extra field "username", that field gets translated, the others from flask-security doesn't.

Any ideas on how I can try to debug that ?

More infos : my form is render by `render_form` from greyli/bootstrap-flask but since every other parts of the forms, except flask-security works, I don't know if that can be the issue, I do remember seeing issues about translations upstream but nothing seemed to help here.

**Comment by jwag956** [comment]
I will definitely look into this. It is a new area for me.
Also - I will be out of town for a few days - so it might take a few days.

Can you add info about your extended form and configuration (such as I18_DOMAIN), and what if any changes to translation files you have made? Also - I assume you are using 3.0.0 version of Flask-Security - and not a fork from the develop branch.

**Comment by rhaamo** [comment]
Hmm, I don't seems to have any I18_DOMAIN or specific config.
I haven't touched the translation files from flask-security so I think the one shipped should be used ?

I am using `git+https://github.com/jwag956/flask-security#egg=Flask-Security-too` in my requirements for the moment because I haven't tested the 3.0.0 (previously I had to use upstream develop branch because of an unreleased fix I needed).

Code is going to be better than a few random extracts so my current translation issue is in this branch https://github.com/rhaamo/reel2bits/pull/49

Don't worry for time delay, it's not a critical thing at all so it will take the time it needs without speeding.

thanks.

**Comment by jwag956** [comment]
Ok - I am just starting to look into this. A simple unit test seems to be doing the correct xlation.

Couple questions for you:
- can you send/post an example of the response you are getting for your form and point out which pieces aren't being xlated?
- can you run your app in a debugger - and set a breakpoint at the 'if' to see if flask-security is registering its domain (this code is in flask_security::core.py)

`        
       @app.before_first_request
        def _register_i18n():
            if "_" not in app.jinja_env.globals:
                app.jinja_env.globals["_"] = state.i18n_domain.gettext
`

thanks!

**Comment by rhaamo** [comment]
Ok I've tried differently than debugger to have more infos:
```
        def _register_i18n():
            if "_" not in app.jinja_env.globals:
                app.jinja_env.globals["_"] = state.i18n_domain.gettext
            else:
                print(f"_ exists: {app.jinja_env.globals['_']}")
                print(f"state.i18n_domain.gettext = {state.i18n_domain.gettext}")
```

Which results in:
```
_ exists: <function _gettext_alias at 0x10cfd50d0>
state.i18n_domain.gettext = <bound method Domain.gettext of <flask_babelex.Domain object at 0x10d03c1d0>>
```

flask_babelex is what I'm using for translations in my app, so it looks like to be overriding "_", which flask_security seems to use.

**Comment by jwag956** [comment]
I have figured this out - looks like i18n of form labels probably has never worked. Very simple fix - I want to improve i18n testing while I am at it.
