### ISSUE TITLE
POST request on /logout should be allowed (at the very least)

### ISSUE THREAD

**Issue by golyalpha** [jwag956/flask-security#112]
Flask-Security should at the very least accept POST requests on the /logout endpoint.  
My reasoning being:
 - Some browsers are starting to prefetch links on a website, which can lead to an accidental logout of the user. (As [this guy](https://twitter.com/Nick_Craver/status/296281730984316928) has already found out.)
 - GET request technically shouldn't perform an action on the server side (can we agree that logging a user out is an action?), therefore I feel POST is more correct here.

In my case, I already have a form in the nav, that sends a post request to the /logout endpoint with the submit button, and it's styled to look exactly as any other item on the navbar. Sure, It's not effortless, but I think the work's kinda worth it.

**Comment by Themayu** [comment]
I am also aware of some users that use DELETE for logging users out, and have begun to follow the same strategy myself. Perhaps this could be a viable option for Flask-Security to support as well?

**Comment by jwag956** [comment]
This is in 3.2.0rc3:
https://pypi.org/project/Flask-Security-Too/3.0.2/#history

please check it out.
As for DELETE - I am not convinced it is quite up to HTTP 1.1 standards- but seems like a reasonable option. If you or someone wanted to issue a PR to make the METHOD configurable (with DELETE not default) I would accept it.
