### ISSUE TITLE
3.2.0 Release

### ISSUE THREAD

**Issue by jwag956** [jwag956/flask-security#118]
I am ready to push 3.2.0 - Tyler - it would be great if you could try 3.2.0rc4 in your application to make sure nothing obvious broke.

I'd like to push this in the next few days....

Thanks!

**Comment by baurt** [comment]
Will do.  I think I have some time tomorrow and Wednesday.  I've tested a little and seems to be functioning, but I will test more in depth tomorrow.

**Comment by baurt** [comment]
From my personal testing, I would say that this is good to release.  I haven't had any issues with the package in a flask app that I have.

**Comment by booherbg** [comment]
@jwag956 -- I'm switching over to your fork so I can take advantage of the authentication tokens (I'm using a SPA after all).

I did a standard install, and can confirm I have what pip thinks is version 3.2.0, but I don't think I have the right version. At a minimum, I see the 'cache.py' file is missing (and my auth tokens are still slow!). Maybe I did something wrong?

```
pip uninstall flask-security
pip install flask-security-too
pip freeze | grep Flask-Security
Flask-Security-Too==3.2.0
cd .direnv/python-3.7.3/lib/python3.7/site-packages/flask_security Tue Jul 09]
69$ ls
babel.py        core.py        __init__.py      registerable.py  translations
changeable.py   datastore.py   passwordless.py  script.py        utils.py
cli.py          decorators.py  __pycache__      signals.py       views.py
confirmable.py  forms.py       recoverable.py   templates
```
Certainly I can just pull from git but I thought I'd bring this up in case there's something else that's misconfigured upstream. I also note that pip thinks there should be a `site-packages/Flask_Security_Too-3.2.0.dist-info` folder, but that doesn't exist (but `site-packages/flask_security` does).

**Comment by jwag956** [comment]
Something is definitely odd - I just did an uninstall/reinstall and worked fine and I have a site-packages/Flask_Security_too-3.2.0.dist-info

any chance you forgot to activate your venv? :-D

**Comment by booherbg** [comment]
yeah, it's definitely weird. I cannot get this to install and a fresh environment either. I can clone just fine, but the installed package itself seems stale.

Maybe you are right. Could it be that pip somehow caches the previously installed flask_security?

**Comment by jwag956** [comment]
you could try pip --no-cache-dir to see if that helps. Very odd since the version numbers are different in any case. If you have a chance - could you zip up the contents of our site-packages/flask_security and send it to me? I will see what version it is...

**Comment by booherbg** [comment]
Weird. It works now. I can't explain it. I installed the original flask-security, then removed it, then installed flask-security-too, and now everything looks ok. I didn't even have to use --no-cache-dir
