### ISSUE TITLE
JSON responses and LazyStrings

### ISSUE THREAD

**Issue by jwag956** [jwag956/flask-security#127]
Turns out that if we get a validation error (which are LazyStrings) and are requesting a JSON response, we get a 500 Json encoding error since LazyString isn't json serializable.

Amazingly this wasn't caught in unit tests, because the unit test code actually overrode the JSONEncoder and  handles LazyStrings.
sigh.

**Comment by brutalsuperman** [comment]
still get 500 on forgot password with password like test@mail

**Comment by jwag956** [comment]
I can't repro this - here is a unit test I wrote:

```
        # Test invalid email format
        response = client.post(
            "/reset",
            data='{"email": "test@mail"}',
            headers={"Content-Type": "application/json"},
        )
        assert response.status_code == 400
        assert response.jdata["response"]["errors"]["email"][0].encode(
            "utf-8"
        ) == get_message("INVALID_EMAIL_ADDRESS")
```

I'll need some code/config to track this down.
