### ISSUE TITLE
No module named 'flask_security.models'

### ISSUE THREAD

**Issue by plasticruler** [jwag956/flask-security#129]
I am using Python `3.6.8` in the virtual environment created whilst following the Quick Start. Same thing happens with Python `3.5.3.`

This error comes up immediately when attempting to run the app.

`Traceback (most recent call last):
  File "appme.py", line 4, in <module>
    from flask_security.models import fsqla
ModuleNotFoundError: No module named 'flask_security.models'
`

The `appme.py` file is copied verbatim from the Quick Start.

**Comment by jwag956** [comment]
Can you verify that you have Flask-Security-Too 3.2.0 installed?

**Comment by plasticruler** [comment]
I followed the steps in the Quick Start. It downloaded the default version. Just did a `pip3 freeze`. It showed
`Flask-Security-Too==3.2.0`

**Comment by plasticruler** [comment]
I could be wrong but further investigation showed the 3.2.0 version to be released on 27 June. The checkin where the file `fsqla.py` starts to appear is dated 9 July.  I'm not that familiar with package management etc but could there be a missing release?

**Comment by plasticruler** [comment]
Ahh yes that appears to be the case. The Quick Start documentation is also dated 9 July. The previous version of this file does not use fsqla, so I'm going to assume I need to use the older Quick Start tutorial until a newer package is released.

**Comment by jwag956** [comment]
Ahh - how quickly we forget. Yes that hasn't been released yet. readTheDocs seems to default to 'latest' rather than 'stable' - you will see that the quickstart guide is different.

You can pip install directly from the master branch rather than going through pypi if you are just starting out. I will probably push another release in a month or so.
