### ISSUE TITLE
Dropping a bit of legacy compatibility

### ISSUE THREAD

**Issue by TaaviE** [jwag956/flask-security#143]
For example there's https://github.com/jwag956/flask-security/blob/master/flask_security/script.py , https://github.com/jwag956/flask-security/blob/master/flask_security/datastore.py#L369 , and quite a few `NotImplementedException`-s.

I'm sure there's more workarounds for ancient dependency versions but maybe those specific ones could be removed?

**Comment by jwag956** [comment]
I am fine removing those 2 - not sure about which Not-Implemented you mean -the ones in Datastore are for requiring concrete datastore classes to implement.
