### ISSUE TITLE
Enabling pool pre-ping by default

### ISSUE THREAD

**Issue by TaaviE** [jwag956/flask-security#144]
Since [Flask-SqlAlchemy 2.4.0](https://github.com/pallets/flask-sqlalchemy/pull/684) it's easy to enable SQL pool pre-pinging that should increase reliability of any services using Flask-Security, it would be a good default in majority of cases. What do you think?

This is how I and some others have done it:
```python3.8
    self.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
        "pool_pre_ping": True,
    }
```

**Comment by jwag956** [comment]
I have put that in some docs recently as suggested ideas. But it isn't really our place to automatically add options to other packages - especially DB..  IMHO.

Yes - it helps flask-security - but it is even more important to the application itself that might well have its own ideas about connections and pools etc.

**Comment by TaaviE** [comment]
Well, it does a tad more than help, currently if any connection in the pool timeouts FS won't recover, there's an issue upstream about that. Though I guess anyone actually encountering it can apply the fix themselves.

**Comment by jwag956** [comment]
And it affects their ENTIRE application. We need to be careful not to delve too much into data stores here - it is already difficult enough to test and keep up. So - I do believe in best practice and documenting that. So we should add that to quickstart and the example app (I thought I had done that already).
