### ISSUE TITLE
Issue with http_auth_required and Flask-Restplus

### ISSUE THREAD

**Issue by koekie** [jwag956/flask-security#166]
I am having issues with the way an unauthenticated request is handled in conjunction with flask-restplus.

Given the following example code
```python
@api.route('/users/<id>', endpoint='user')
class UserAPI(Resource):
    @http_auth_required
    @permissions_accepted('user_read', 'user_read_all')
    @api.marshal_with(user_get)
    @api.response(200, "Success")
    def get(self, id):
        user = do_something_to_get_user()
        return user
```
When I do a GET request on this endpoint I get the following stacktrace (for example by doing this: `curl -X GET "http://localhost:5000/api/v1/users/1" -H  "accept: application/json"`):
```
[2019-08-16 17:08:27,192] ERROR in app: Exception on /api/v1/users/1 [GET]
Traceback (most recent call last):
  File "/home/mkoek/prog/taskmanager/venv/taskmanager/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mkoek/prog/taskmanager/venv/taskmanager/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mkoek/prog/taskmanager/venv/taskmanager/lib/python3.6/site-packages/flask_restplus/api.py", line 330, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/mkoek/prog/taskmanager/venv/taskmanager/lib/python3.6/site-packages/flask_restplus/api.py", line 351, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/mkoek/prog/taskmanager/venv/taskmanager/lib/python3.6/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Response' is not JSON serializable
```

I think what we see is happening here is, that _security._render_json (at https://github.com/jwag956/flask-security/blob/master/flask_security/decorators.py#L75) returns the following tuple down the decorator line, in this case it is this:
```(<Response 81 bytes [200 OK]>, 401, {'WWW-Authenticate': 'Basic realm="Taskmanager Login Required"'})```
In the case the `accept: application/json` is set, flask-restplus expects either a Response object or a sequence that should be serialized to json. In this case it received a sequence with a response object in it and got confused ;)

I think in this case (the want_json path) it is good idea to just pass a Response object back with the correct body, headers and response code. This gives the least chances of breakage when this extension is used together with other flask extensions.

Also when having a look inside _security._render_json -> views.default_render_json (at https://github.com/jwag956/flask-security/blob/master/flask_security/views.py#L130)
* You cannot pass the status code to jsonify (at least in recent versions) of Flask in the way you do right now. 
* The user argument is not used. Is this reserved for future plans?

I am preparing a pull request, but I wanted to make sure to be on the page on beforehand. Is it OK if I implement in default_render_json to only return a Response object or maybe create a specific method for the want_json case? Should a 401 response have an empty body or should there be a message saying that it was an unauthenticated request?

**Comment by jwag956** [comment]
Thanks for the detailed analysis - and thanks for trying out Flask-Security-Too.

Not in any order - the 'user' argument isn't used in this default_render_json - but is part of the signature so that callbacks will get it if they need it. The idea here is that applications can (and probably should) provide their own so that they can have a uniform API response.

Note that the 'code' isn't being sent to jsonify - default_render_json is returning 'something that Flask can turn into a response' - as defined here: https://flask.palletsprojects.com/en/1.1.x/quickstart/#about-responses

So possibly flask-restplus doesn't accept the same types of responses as Flask - but I am fine with a PR that returns a complete response (using make_response?)

**Comment by koekie** [comment]
Created PR #167
