### ISSUE TITLE
`Required` class change causes issues when migrating

### ISSUE THREAD

**Issue by TaaviE** [jwag956/flask-security#170]
I think people would appreciate if the changes to the `Required` class from `flask_security.forms` could be somehow be listed as a breaking change, removed in general (if people should use `wtf`'s `DataRequired` instead) or marked deprecated. Right now using `Required()` on a form field causes a generic error like this which is not ideal:

```
  File "~/Project/.venv/lib/python3.7/site-packages/flask_security/forms.py", line 76, in __init__
    self._original_message = kwargs["message"]
KeyError: 'message'
```

**Comment by jwag956** [comment]
Interesting - yes - a change for i18n I made assumes that every validator has a 'message' keyword - which all the current uses do. Is there a use case to not have a message? I can easily throw an exception which would at least tell user what is going on...

**Comment by TaaviE** [comment]
>  Is there a use case to not have a message?

There's no message in the official documentation(s), that's what many use. I think it defaulted to "This field is required" as well, but I'm not sure.

**Comment by jwag956** [comment]
got it - I'll make it backwards compatible

**Comment by TaaviE** [comment]
Thanks!

**Comment by jwag956** [comment]
thank you... I/we need all the testing we can get - there are so many changes - mine as well as all the PRs that have never been released from the mainstream FS.
