### ISSUE TITLE
No auth token in 3.3 rc3?

### ISSUE THREAD

**Issue by acidjunk** [jwag956/flask-security#187]
I noticed a change while trying the new RC3.
I didn't change the SPA that is using the login manager, but with the last version of Flask-Security-Too the login suddenly doesn't work anymore.

Not sure if I needed to change something on my backend?
https://travis-ci.com/acidjunk/improviser/jobs/239315478

New, commit sha: 71f409774f3666bc16c60c9bbab6db44c55437db
```
{
  "meta": {
    "code": 200
  }, 
  "response": {
    "csrf_token": "IjAzNTIyMTllY6FkMDM1MmRhZmUyZmZmNDU0NDM1OGY5NDYzNWVkODIi.XYxryQ.1Pt4cDMwujN6uUpDFoWN5Uty0UY", 
    "user": {
      "id": "4af1f7f6-4781-4607-bf6c-f0388f7f4527"
    }
  }
}
```

Older response, sha: 560a401545006cf43b7047a16e944cf78ea75070
```
{
  "meta": {
    "code": 200
  }, 
  "response": {
    "csrf_token": "ImNmMjM4ODVkYjRlOTY0ODk4NzQ0MjNlOWE2OGE0NWJiZWVjM2M1NGMi.XYx3ow.lnThUkbuOz59ZhFF_BGFTSKPaGI", 
    "user": {
      "authentication_token": "WyI0YWYxZjdmNS90NzgxLTQ2MDctYmY2Yy1mMDM4OGY3ZjQ1MjciLCIkNSRyb3VuZHM9NTM1MDAwJGIveHN2NjdyYjZrM1B3Zi4kdFkzTXpMMDBkcnVqd21ramxkb3JrYzNPNFBYNGJROEk1QW1Jdk5TT2RLMyJd.XYx3ow.s82HkXwm9_pIs_85-6H7eu6Qehg", 
      "id": "4af1f7f6-4781-4607-bf6c-f0388f7f4527"
    }
  }
}
```

**Comment by jwag956** [comment]
As noted in the CHANGES - the default behavior has changed - you must now either:
1) explicitly request the auth token (add ?include_auth_token) OR
2) set the SECURITY_BACKWARDS_COMPAT_AUTH_TOKEN=True

Always sending back the auth token is a security issue for those application that aren't using it (such as normal session based apps).

**Comment by acidjunk** [comment]
Thanks, fixed indeed. :)
