### ISSUE TITLE
Branding issues

### ISSUE THREAD

**Issue by jdevera** [jwag956/flask-security#190]
Thank you for this fork and for taking care of such an important project.

I think some elements could change to make it clearer that fork is now its own thing.

* The repo name should probably reflect the project name, `flask-security-too`
* There should be a link to the PyPI package
* The README should mention the PyPI package, even if as a oneliner with pip install instructions.

**Comment by jdevera** [comment]
Awesome response time. Thank you!

**Comment by jwag956** [comment]
thank you - nice small improvement.

I decided not to change repo name at this time - I am worried it will cause even more confusion.

Have you tried using my fork? or were you just poking around?

**Comment by jdevera** [comment]
> Have you tried using my fork? or were you just poking around?
I'm working on a migration to 3.8 and the dependency analysis led me to the original repo. I do not have any confidence in the future of that project, unfortunately, after seeing the failed attempts to revive it. So for now just poking around. Test do not seem to run in Python 3.8 yet due to `pony` not being ready for python 3.8 but from what I read they will have a new release soon.
