### ISSUE TITLE
Question: MongoEngine instead of Flask_MongoEngine

### ISSUE THREAD

**Issue by mol1narius** [jwag956/flask-security#193]
In the docs it says that Flask_MongoEngine is supported. Since Flask_MongoEngine was not maintained for more than 1 year, I asking myself if it is possible to use MongoEngine itself instead.

In the minimal example in [your documentation](https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-mongoengine-application), the `MongoClient` is used to connect to the database. Is there any reason to not just use MongoEngine instead of Flask_MongoEngine?

**Comment by jwag956** [comment]
Of course all this predates my maintaining of this fork.
In general, the Flask- packages that wrap underlying functionality vary from very thin wrappers, to ones with extended functionality. At a minimum, the wrappers deal with Flask's multi-app/dependency injection model and making sure different requests get their own local proxy of the underlying resource. 

That being said - if you don't have multiple 'apps' in the same namespace, (not sure who does) then it would probably be pretty easy to avoid Flask-MongoEngine. Recently - I hooked up flask with dynamodb - and decided NOT to use Flask-Dynamo. 
I looked briefly at Flask-Mongoengine - and it does have a bunch of additional functionality, but nothing that seems all that important.

So - bottom line - I don't think it would be difficult at all to just use mongoengine -
