### ISSUE TITLE
Email templates with extra context

### ISSUE THREAD

**Issue by rhaamo** [jwag956/flask-security#198]
Is it possible to pass extra context to the rendering of the email templates ?

I would like to use some extra variables in the templates for customization, I've tried to look at the code but I don't see a way to do that.

**Comment by jwag956** [comment]
Yes - it appears to be undocumented - but there is a mail_context_processor that will be called whenever an email is sent. See: https://flask-security-too.readthedocs.io/en/stable/customizing.html#views
for some details on context_processors.

**Comment by rhaamo** [comment]
works great, thanks !
