### ISSUE TITLE
sqlalchemy is a hard requirement now

### ISSUE THREAD

**Issue by stefaang** [jwag956/flask-security#201]
As of jwag956/flask-security/pull/161, the models.fsqla is imported in the main `__init__.py`.
This makes sqlalchemy a hard requirement, while I'd like to use a mongo backend (mongoengine) instead...
I think it is not intended to pull in this new requirement, but if it is, it should be documented.

**Comment by jwag956** [comment]
Oh - no - not my intent... I will fix that.. thanks!
