### ISSUE TITLE
2FA - Google Authenticator (TOTP) broken due to regenerated secrets upon finalization

### ISSUE THREAD

**Issue by Kishi85** [jwag956/flask-security#215]
The TOTP secrets are being regenerated upon changing the two-factor method, even if the new method uses TOTP (google_authenticator) and the current TOTP secret (and QRcode) has been verified by the user during the validation step. 
This will cause any verification afterwards to fail due to new (unverified) TOTP secrets on the user and not the ones the user verified during validation.  

See: twofactor.py - complete_two_factor_process(...) - Line 151-152

This is related to #160

**Comment by jwag956** [comment]
Yup - that code is just in the wrong place (and that's my fault - the original PR didn't have that).

**Comment by Kishi85** [comment]
The tf_totp_secret should only be updated on the user when the 2fa setup finishes. I've implemented a proper fix for this by introducing a session variable for the tf_totp_secret while the setup process is running. Feel free to look at my PR and merge if it's up to your Standards (tested and works for my use-cases, but maybe there's a better way).

**Comment by jwag956** [comment]
The original PR (long ago) had this approach - but I don't think its a good approach - the session is serialized into the session cookie - which is signed but NOT ENCRYPTED. Thus I believe this would expose the totp_secret to anyone with the cookie. You can see this by taking your cookie (from say your browser debug) and plugging it into:
https://www.kirsle.net/wizards/flask-session.cgi

I think though the fix would be to move the code that generates a new totp_secret into the form.validate_on_submit() block of code - it would seem like anytime the user is enabling or changing the config - we should generate a new totp.

**Comment by Kishi85** [comment]
I didn't think about that in my first implementation, but you're right, that's not the best approach. Moving the code that generates the secret to form.validate_on_submit() after selecting the method should be a good and viable way to do it. That means it would still take two commits to the DataStore to successfully enable 2FA, something which I'd like to have for one of my use-cases but so far I don't have a better solution than your proposal. I'll update this issue should something come to mind.

**Comment by jwag956** [comment]
So - are/can you provide a PR - or do you want me to do that?

Also - can you elaborate on your comment about 2 DB commits - I don't really think much about that for very rare occurrences such as this - what is your concern?

**Comment by Kishi85** [comment]
I've done a new PR for this, just like we discussed with the TOTP being regenerated after the method is selected (minus the case where a phone number is submitted afterwards). 

The 2 commits case is just a special problem for this one project I'm doing where a revisioned storage is used for the configuration and flask-security cannot commit on it's own without the user confirming in another dialog (the QRcode cannot be created during setup in this case due to missing data on the user) but i'll find a way around that within the projects codebase.
