### ISSUE TITLE
help testing flask-security pytest

### ISSUE THREAD

**Issue by johndiego** [jwag956/flask-security#219]
I 'm problem for testing flask-securty with pytest
My config is 
```
class TestingConfig(Config):
    POSTGRES = {
        'user': os.environ['DB_USER'],
        'pw': os.environ['DB_PASS'],
        'db': 'tests',
        'host': os.environ['DB_SERVICE'],
        'port': os.environ['DB_PORT'],
    }
    TESTING = True
    LOGIN_DISABLED = True
    DEBUG=False
    WTF_CSRF_ENABLED=False
    # SERVER_NAME='localhost'
    SQLALCHEMY_DATABASE_URI = 'postgresql://%(user)s:%(pw)s@%(host)s:%(port)s/%(db)s' % POSTGRES
    SQLALCHEMY_ECHO = False
```
MY conftest

```
import pytest
from flask import Flask,template_rendered
from app_factory import create_app
from flask_security.utils import login_user
from blueprints.auth.models import User
from ext.db import db 
from ext.config import config
from sqlalchemy import event
from sqlalchemy.orm import sessionmaker

@pytest.fixture
def captured_templates(app):
    recorded = []

    def record(sender, template, context, **extra):
        recorded.append((template, context))

    template_rendered.connect(record, app)
    try:
        yield recorded
    finally:
        template_rendered.disconnect(record, app)


@pytest.fixture
def dbapp(app):
    db.drop_all()
    db.create_all()
    yield app

@pytest.fixture(scope="session")
def app(request):
    return create_app("test")
```

My test

```
def test_login_logout(dbapp,client,captured_templates):
    pwd = hash_password('11')
    user  = User(**{ 'active':True,'username':'teste2','email':'teste@teste.com.br','password':pwd})
    db.session.add(user)
    db.session.commit()
    resp = client.post(url_for('security.login'), data=dict(
        username='teste2',
        password='11'
    ))
    template, context = captured_templates[0]
    print(context)
    assert resp.status_code == 200
    # assert 'errors' in context['login_user_form']
    assert template.name == "pessoa.html"
```
Testing show error!!
```
dbapp = <Flask 'app_factory'>, client = <FlaskClient <Flask 'app_factory'>>
captured_templates = [(<Template '/security/login.html'>, {'APP': 'APP', 'csrf_token': <function generate_csrf at 0x7f803f61e440>, 'current_user': <flask_security.core.AnonymousUser object at 0x7f803c468750>, 'g': <flask.g of 'app_factory'>, ...})]

    def test_login_logout(dbapp,client,captured_templates):
        pwd = hash_password('11')
        user  = User(**{ 'active':True,'username':'teste2','email':'teste@teste.com.br','password':pwd})
        db.session.add(user)
        db.session.commit()
        resp = client.post(url_for('security.login'), data=dict(
            username='teste2',
            password='11'
        ))
        template, context = captured_templates[0]
        print(context)
        assert resp.status_code == 200
        # assert 'errors' in context['login_user_form']
>       assert template.name == "pessoa.html"
E       AssertionError: assert '/security/login.html' == 'pessoa.html'
E         - /security/login.html
E         + pessoa.html
```

**Comment by jwag956** [comment]
I don't see any configuration change that would change the template names?

**Comment by johndiego** [comment]
I'm default flask-security, 
i need examples with how can testing flask security with pytest.

**Comment by jwag956** [comment]
A couple things here - I don't know why you would think the login template would be called "pessoa.html" - with the default configuration it is using the supplied template called security/login.html - which is what you are getting. So your test seems fine.

Perhaps more importantly - just what are you trying to test? If you are trying to test flask-security - then look at all the tests in the source code. If you are trying to test your application's use of Flask-Security - then you should be treating FS as a black-box. For example if you want to replace FS's templates with your own - then you can easily test that by looking at the response to a GET. You shouldn't really care HOW flask-security decides to  render templates.

**Comment by johndiego** [comment]
thanks for repply!!
I 'm testing my routes but , in my testing dont work
I nedd testing my models without being logged in, how i can make this?
if look my error  flask securty don't  accepts , aways redirect my route /security/login;
In documentation it is in testing config
 LOGIN_DISABLED = True
 DEBUG=False
 WTF_CSRF_ENABLED=False
How i can testing my routers without logged?

**Comment by jwag956** [comment]
There are a lot of variables here. LOGIN_DISABLED is a Flask-Login config - and only applies to the @login_required decorator. None of the Flask-Security decorators look at that variable.

The best answer - is that you should 'log' in as part of your tests. If you are getting redirects - then you are logging in correctly.

Logging in is easy:
    data = dict(email=email, password=password, remember="y")
    return client.post("/login", data=data, **kwargs)

where client is app.test_client() (look in Werkzeug docs for this).

**Comment by johndiego** [comment]
you have sample code?

**Comment by jwag956** [comment]
So I do 2 different things in my app which uses flask-security - for unitttests where I just want to check routing etc I fake out login, for integration tests where I really want to test the real thing including really authenticating - I actually login (after having set up some test users).
This could use some additional documentation - so I will look into adding that.
However - for pure unittests - 

First I have a simple method that creates an (in-memory) user:

```
def create_fake_user(email='unittest@me.com', userid=1, roles=None):
    """ Create fake user optionally with roles """
    user = dbmodel.User()
    user.email = email
    user.id = userid
    user.password = 'mypassword'
    user.active = True
    if roles:
        user.roles = []
        if isinstance(roles, str):
            roles = [roles]
        for role_name in roles:
            role = dbmodel.Role()
            role.name = role_name
            user.roles.append(role)
    return user
```

Next I have a simple method that fakes out the authentication process:

```
def set_current_user(app, user):
    """ Set up so that when request is received, the token will cause 'user' to be made the current_user """
    def token_cb(request):
        if request.headers.get('Authentication-Token') == 'token':
            return user
        return None

    app.security.login_manager.request_loader(token_cb)
```
In conftest.py I create a fixture (this is simplified from what I do):

```
@pytest.fixture
def myapp():
    return app()  # create an instance of your app - with TESTING=true
```

Finally a simple test:
```
def test_add_image_bad_purpose(myapp):
    """ Test passing missing or unknown purpose throws 400 """

    user = create_fake_user(roles=["basic"])
    set_current_user(myapp, user)

    resp = myapp.test_client.post('/api/whatever',
                                   headers={app.config['TOKEN_AUTHENTICATION_HEADER']: 'token'},
                                   data=dict({'yourparams': 'whatever'}))
```

Hope that helps.

**Comment by johndiego** [comment]
I'm tring with pytesting

**Comment by johndiego** [comment]
Thanks @jwag956  working =)
