### ISSUE TITLE
2FA setup not triggered after registration when SECURITY_TWO_FACTOR_REQUIRED is True

### ISSUE THREAD

**Issue by kuba-lilz** [jwag956/flask-security#223]
I would expect that with `'SECURITY_TWO_FACTOR_REQUIRED' = True` when user tries to access application after registration, she should be redirected to 2FA setup page.

What I see is that immediately after registration user gets logged without being asked for 2FA setup. Only after logging out manually and trying to log in again user gets redirected to 2FA setup page.

(When using confirmation email result is similar - after clicking on confirmation link user gets logged in and needs to manually log out and log in again for 2FA setup to get triggered).

I understand 2FA is still in works, so perhaps this will get classified as `under development` rather than `bug`, but wanted to make sure developers are aware of this behavior.

**Comment by jwag956** [comment]
The answer of course is 'both' - the reason I marked it as experimental is that it was a very large change that needed a lot more work to get it fully integrated.
Let me look at what it would take to fix this.

**Comment by kuba-lilz** [comment]
An ugly hack I used to cause behavior I'm after was to call `flask.session.clear()` if response comes from `POST /register` endpoint or `GET /confirmation` endpoint in my after request handler - forcing user to be logged out.
Hardly pretty, though.

**Comment by jwag956** [comment]
So you are using 2FA? great - I'll work on that next - try to get these few things into a 3.3.2 release in the next few days.....
