### ISSUE TITLE
empty current_user.tf_primary_method inconsistent between required and optional 2FA

### ISSUE THREAD

**Issue by kuba-lilz** [jwag956/flask-security#226]
When 2FA is optional and user with no 2FA method set up accesses 2FA setup endpoint, in jinja template `current_user.tf_primary_method` is None.

But when 2FA is required and user with no 2FA method accesses 2FA setup endpoint,
in jinja template `current_user.tf_primary_method` is an empty string.

That's a bit inconsistent. In database `tf_primary_method` column is declared as nullable.
It doesn't matter if my user ORM declares:
```python
tf_primary_method = sqlalchemy.Column(sqlalchemy.String(140))
```
or
```python
tf_primary_method = sqlalchemy.Column(sqlalchemy.String(140), nullable=True)
```
in both cases behavior is as described above.

I assume something inside 2FA checking logic for 2FA required setting casts None to an empty string. Wouldn't it be better to make the behavior consistent in both enabled and required cases?

**Comment by jwag956** [comment]
Interesting - I can't repro this - I had 2FA required, and went new new user registration, confirmation. If 2FA is required, then there shouldn't be any way for a user to be authenticated prior to tf-setup - so current_user would be pointing at anonymousUser - which shouldn't even have a tf_primary_method. So I am a bit confused as to how you set up your second test case.?

**Comment by kuba-lilz** [comment]
Ah, you are right - current_user is an instances of <flask_security.core.AnonymousUser>.

And I suspect reason I get an empty string is due to Jinja's behavior:
https://jinja.palletsprojects.com/en/2.10.x/templates/#variables
> If a variable or attribute does not exist, you will get back an undefined value. (...) the default behavior is to evaluate to an empty string if printed or iterated over, and to fail for every other operation.

I tried referencing some random non-existing members inside the tf-setup template and got same behavior.

Just for reference - here's what I added to tf-setup template:
```
Who are you? {{ current_user }}
Your tf method is None? {{ current_user.tf_primary_method == None }}
Your tf method length is: {{ current_user.tf_primary_method | length }}

Your random_field is None? {{ current_user.random_field == None }}
Your random_field length is: {{ current_user.random_field | length }}
```

and here's what code gets evaluated into:
```
Who are you? <flask_security.core.AnonymousUser object at 0x132f864e0> 
Your tf method is None? False 
Your tf method length is: 0 
Your random_field is None? False 
Your random_field length is: 0
```

So yeah, the problem exists between the chair and the keyboard, sorry about that ><
