### ISSUE TITLE
CSRF cookie not set on remembered login

### ISSUE THREAD

**Issue by Kishi85** [jwag956/flask-security#232]
Upon restarting a remembered session (closing and re-opening the browser after logging in with remember_token) the CSRF cookie is not set again for the new session due to the session missing the key "fs_cc" for the CSRF cookie op and therefore the response is sent back without adding it in csrf_cookie_handler. 

This breaks AJAX applications using cookies for sending the CSRF header back to the server (e.g. axios).

**Comment by jwag956** [comment]
Ohh - nice catch...  seems like we should generate a new csrf_cookie on new login?

**Comment by Kishi85** [comment]
> Ohh - nice catch... seems like we should generate a new csrf_cookie on new login?

1. On a "normal", non-token login it is already done that way. 
2. On auth token logins I don't think it would be strictly necessary to send the cookie (it most likely won't hurt and will be unused in the worst case)
3. Logins with remember_token are special, as in they do not utilize "utils.login_user" but we want the same behaviour as it provides.

"utils.login_user" calls session['fs_cc'] = 'set', which in turn enables the csrf_cookie_handler to function properly on the first request after login. So in order to make this work the way it should we'd either have to:

1.  Have the csrf_cookie_handler treat 'fs_cc' not in session the same way as 'set' (or change the default), which would cause all first responses within a session to have a csrf_cookie sent and also have the cookie handling isolated to the csrf_cookie_handler

2. Set session['fs_cc'] = 'set' everywhere an implicit login happens, either with remember_token or any other auth token or both.

**Comment by jwag956** [comment]
Need to play with this - in general - I don't like, and have been trying to fix - sending security material when the client/user isn't expecting it. For example - for auth token logins - we still send a session cookie - which I think is a (small) security risk. CSRF cookies less so - but still - I would prefer not - however - I believe we are doing it today - so something else to put in the mix.

It might be fine to simply use 'absense of fs_cc' as a trigger to send it - need to think that through.

**Comment by Kishi85** [comment]
I think I found a nice solution for this issue that should be in line with your requirements. I'll post a pull request in a few minutes but it's basically boiling down to checking if the user was successfully logged in with remember_token and then setting the op to 'set' in csrf_cookie_handler. Which would only set the csrf_cookie if the login was successfully done utilizing the remember_cookie and in no other case as either those preconditions are not met or fs_cc is already in a not None state.
