### ISSUE TITLE
Remember cookie uses primary user id

### ISSUE THREAD

**Issue by jwag956** [jwag956/flask-security#239]
The Flask-Security documentation says it uses the 'alternative token' feature of Flask-Login - which basically adds a second unique userid so that it is possible to reset/invalidate login cookies without changing the base user id.
But I can't find any indication that was ever actually done. FS seems to use the default Flask-Login get_id() which returns user.id

This is bad both for the above reason, as well as not all databases make any guarantee that a primary key won't be reused - so if a user is deleted and a new one created - it COULD have the same user.id - in that case the old users remember cookie could be used to log in to the new user.

Unless I am missing something.

**Comment by Kishi85** [comment]
I've checked upstream and basically this just puts the internal user.id into the cookie alongside a digest to be able detect tampering. LoginManager should be extended in a way that incorporates fs_uniquifier for cookie digest calculation and also additional encryption applied (again with fs_uniquifier) to avoid leaking a plain text user.id in the cookie name.

**Comment by Kishi85** [comment]
I'd suggest something like that (if you want me to continue working on the implementation I can do that tomorrow probably but I'm lacking time right now):
```diff
diff --git a/flask_security/core.py b/flask_security/core.py
index 1dc4ded..1009212 100644
--- a/flask_security/core.py
+++ b/flask_security/core.py
@@ -19,7 +19,7 @@ import sys
 import pkg_resources
 from flask import _request_ctx_stack, current_app, render_template
 from flask_babelex import Domain
-from flask_login import AnonymousUserMixin, LoginManager
+from flask_login import AnonymousUserMixin, LoginManager as _LoginManager
 from flask_login import UserMixin as BaseUserMixin
 from flask_login import current_user
 from flask_principal import Identity, Principal, RoleNeed, UserNeed, identity_loaded
@@ -523,6 +523,24 @@ def _context_processor():
     return dict(url_for_security=url_for_security, security=_security)
 
 
+class LoginManager(_LoginManager):
+    def _load_from_cookie(self, cookie):
+        # TODO: Decrypt the cookie with SECRET_KEY
+
+        # TODO: Verify the users cookies fs_uniquifier digest
+
+        # Pass it along to flask-login
+        super()._load_from_cookie(cookie)
+
+    def _set_cookie(self, response):
+        super()._set_cookie(response)
+        # TODO: Add another fs_uniquifier based digest
+
+        # TODO: Encrypt the cookie with SECRET_KEY
+
+        # TODO: Set the updated cookie
+
+
 class RoleMixin(object):
     """Mixin for `Role` model definitions"""
 

```

**Comment by jwag956** [comment]
Hmm - we already create a LoginManager - see core::_get_login_manager().

Also - seems like we can do this just using the documented 'Alternative Token' ideas - basically we need a get_id() that encrypts the fs_uniquifier (using SECRET_KEY) and returns that (might as well as the user.id also). Then modify the existing _user_loader() to decrypt and look up.
Of course with all kinds of backwards compat for old style rememberme and apps that don't have fs_uniquifier field.

No rush if you want to work on this. This will take a bunch of testing, some documentation updates etc.

**Comment by Kishi85** [comment]
The main problem here is the way the remember_cookie data is determined:
```python
data = encode_cookie(text_type(session['user_id']))
```
to modify the value in the cookie we'd have to change the sessions user_id which could have implications if it is used anywhere else. That's why I proposed just modifiying the way the cookie is handled, which requires subclassing LoginManager and just modifying the way the cookie is set and retrieved. I'll see how far I can get with that approach but it should be fairly easy get something backwards compatible using that approach and maybe even something upstream could include in one way or another.

**Comment by jwag956** [comment]
I don't think we do anything with that - all that is LoginManager - using the return value of get_id().
The reason I am reluctant to subclass LoginManager is that we will be using internal fields and possibly someone is assuming we are using a 'public interface' LoginManager. Who knows - probably break someone someplace!

**Comment by Kishi85** [comment]
> I have been doing more digging - looks like the remember cookie is in fact encrypted (Flask-Login does that using 'encode_cookie' - so that good (the session cookie that Flask creates is just signed).

If you look at the session cookie, it contains "<user.id>|<digest>" right now as that's what encode_cookie does. So the user_id is still readily visible in the cookie value. While trying to come up with a solution for this I haven't found a single instance where flask-login uses reversible encryption (like AES), so that means we'd have to add cryptography to the requirements and implement the cookie value encryption using that. 

Also I'd never put the fs_uniquifier in there directly (unless I misunderstood something completely, it is akin to a password of sorts which is used to determine auth_tokens for the user), rather use that value for digest calculation, doing the reversible encryption using SECRET_KEY instead.

**Comment by jwag956** [comment]
I think we are overthinking this - but I welcome the discussion. Neither user.id nor user.fs_uniquifier are secrets - they are just ways to identify a particular user. They have the added benefit of not being PII (personally identifiable information). Knowing either of those things doesn't let you do anything (you can't log in with them). For both session cookies and auth tokens - the 'security' is in that they are signed in a way that makes them un-alterable. The contents just has to have something that allows for DB access. This is also how JWTs work (they aren't encrypted).

So I am not worried that in the session cookie someone could see the fs_uniquifier (or the current user.id). I believe that fs_uniquifier is in fact exactly what the Flask-Login documentation means by an alternative-token.

I think the rationale for the remember cookie being encrypted is that it lasts a LONG time.

**Comment by Kishi85** [comment]
Thanks for clarifying this. I agree that using fs_uniquifier shoud be sufficient.

**Comment by Kishi85** [comment]
Implementing this just using get_id and modifying the user_loader was rather simple. I'll put up a PR once I'm done testing my changes.

**Comment by rrrealman** [comment]
@jwag956 @Kishi85 You've done great work related to this issue, thank you a lot. You just need to refine it slightly. 
Assume #313 issue. I've done all according to official documentation and it doesn't work. This result is direct consequence of premature embodiment of `get_id` method. Implementing your own `get_id` method prohibits doing that by any user of Flask-Security. I think, we need to incorporate this great leverage of `fs_uniquifier` along with previous opportunity to redefine `get_id` method. What is your opinion about it?
