### ISSUE TITLE
Role joining is not model agnostic

### ISSUE THREAD

**Issue by pffs** [jwag956/flask-security#249]
We tried replacing flask-security in our project, however our project's User model does not have a sqlalchemy relationship for roles, it's a hybrid_property method on the class.

The changes from https://github.com/jwag956/flask-security/commit/32968e593d2f7c82ed2767b1e0d7927f3edfffaa assumes that if `roles` is defined as an attribute on the User class that it must be a relationship and thus joinable, which isn't always a safe assumption. 

I'm not sure what the best option here is outside of testing to see if the `roles` attribute is specifically a `sqlalchemy.orm.relationship` prior to forcing the relationship to be joined or if in our case we need to not have a `roles` attribute and override something somewhere on how the datastore gets roles for a user.

**Comment by jwag956** [comment]
Hmm, interesting - that PR I picked up from the old Flask-Security (it hadn't been merged yet).
This was a nice DB optimization - but that shouldn't cause applications to break.

Any chance you could post some/all of your user model so I could write a test?

**Comment by pffs** [comment]
Our particular application has some clunky things is does with roles (our `roles` table actually consists of roles and permissions which are can also inherit from each other, so the `roles` attribute on the `User` model actually is doing the recursion and filtering to get the actual roles and not permissions).

I could see someone potentially having a custom getter for roles though which would break, so something like this (sort of related to what we are doing):

```python
class Role(Base):
    id = Column('id', Integer(), primary_key=True, nullable=False)
    description = Column('description', String(128), nullable=False)
    name = Column('name', String(128), nullable=False)
    category = Column('category', Integer(), default=2, nullable=False)


class User(Base):
    id = Column('id', Integer(), primary_key=True, nullable=False)
    first_name = Column('fname', String(25), nullable=False)
    last_name = Column('lname', String(25), nullable=False)
    username = Column('username', String(25), nullable=False)

    _roles = relationship(Role, secondary='mtm_user2role')

    @hybrid_property
    def roles(self) -> List[Role]:
        """Returns only roles that are category 2!"""
        return [role for role in self._roles if role.category == 2]
```

In this case the joinable attribute isn't `roles` but the private `_roles`. 

I could potentially see another case where perhaps the `roles` attribute is a `synonym` for something else (maybe the application already had a permission-esque setup and `roles` was added to allow `flask-security` to work). I haven't tested that, but I would suspect you might run into issues trying to join against a synonym vs the relationship object as well.

**Comment by jwag956** [comment]
Thanks - I suppose a really simple fix is to add a config variable and not try to figure out all the possible ways it might break -just make it easy to turn off!

**Comment by pffs** [comment]
That would work for me, could just have a `SECURITY_JOIN_USER_ROLES` as a boolean or something, and attempt to force the join type when True, and leave it with a default of True since I rather imagine most people are going to be following the typical user/role class structure. 

Thus far I think you'd only really need to modify the `find_user` and `get_user` methods to look at that, really just change https://github.com/jwag956/flask-security/blob/master/flask_security/datastore.py#L333 and https://github.com/jwag956/flask-security/blob/master/flask_security/datastore.py#L378 to something like
```python
if current_app.config['SECURITY_JOIN_USER_ROLES'] and hasattr(self.user_model, "roles"):
```

**Comment by jwag956** [comment]
Yup - easy. Do you want to issue a PR - otherwise I'll get to it in a few days....

**Comment by pffs** [comment]
I'll put in a PR for it here in a bit.
