### ISSUE TITLE
Custom fields in registration forms not passed to create_user?

### ISSUE THREAD

**Issue by kuba-lilz** [jwag956/flask-security#251]
My understanding of https://flask-security-too.readthedocs.io/en/stable/customizing.html#forms is that if I create custom registration form, custom fields content should be passed to `UserDatastore.create_user`. I wasn't able to get this to work, though.

Here's what I tried:
```python
# Custom registration form
class ExtendedRegisterForm(flask_security.RegisterForm):

    domain = wtforms.StringField('Domain: ', [wtforms.validators.Length(min=5)])


# Tell flask security to use custom registration form
flask_security.Security(
        application, user_datastore,
        register_form=ExtendedRegisterForm)


# Our datastore class
class CustomUserDatastore(flask_security.datastore.SQLAlchemySessionUserDatastore):
    """
    User datastore that defines create_user logic.
    """
    def __init__(self, session_factory, user_model, role_model):

        super().__init__(session_factory, user_model, role_model)
        self.session_factory = session_factory

	def create_user(self, **kwargs):

            import pprint
	    
	    print("**kwargs before modification")
	    pprint.pprint(kwargs)

	    kwargs = self._prepare_create_user_args(**kwargs)
	    
	    print("kwargs after _prepare_create_user_args")
	    pprint.pprint(kwargs)

	    user = self.user_model(**kwargs)
	    self.put(user)

	    return user
```

Here's relevant part of registration template
```html
{{ render_field_with_errors(register_user_form.domain, placeholder="workspace-url") }}
```

I can confirm that Flask Security uses my form - it complains if Length(min=5) validation fails.
But printing out `kwargs` inside `create_user`, `domain` is not available.
`kwargs` passed to `create_user` contain only email and password, `_prepare_create_user_args` adds to them optional flask security fields.
Am I missing something? Is this data available somewhere else?

**Comment by jwag956** [comment]
So there is one piece of magic (that has been in since the beginning) - the call to create_user is starts with:
```
register_user(**form.to_dict())
# which calls
_datastore.create_user(**kwargs)
```
And to_dict() is a method in RegisterForm that takes kwargs and ONLY passes those that are attributes on the UserModel.
So the question is - have you already added that to User?

**Comment by kuba-lilz** [comment]
Ah, didn't realize fields have to exist on UserModel. Not quite what I hoped for, as I would like to use this data for something else than saving it inside User object, and thus adding field on UserModel isn't the best fit, but it indeed worked as you described. Thank you for your help!

**Comment by jwag956** [comment]
Well - for create_user they do - but as part of your validator on your registration form - you can have any fields you want and perform any sort of validation you need. Is there a reason that isn't an appropriate place?

**Comment by kuba-lilz** [comment]
When registering a user I would like to create some related objects based on data in registration form.

**Comment by jwag956** [comment]
Ok - possibly we could extend the user_registered signal to include the form kwargs? 

It would require passing the form to register_user() - doing the to_dict() before calling create_user - and passing all fields to the user_registered() signal - seems doable and useful.

Possibly change to_dict() to take a parameter - only_user=True??

**Comment by kuba-lilz** [comment]
Actually... it just occurred to me that I can overwrite `to_dict` inside my own registration form class

**Comment by jwag956** [comment]
Yes you can - but I think you will get DB errors (for sqlachemy) if you pass it any fields that aren't in the schema.... what am I missing?

**Comment by kuba-lilz** [comment]
Ah, just rewriting `to_dict` to pass everything isn't that easy - as datastore tries to use these arguments.
So a more structured approach would be better ^^

**Comment by kuba-lilz** [comment]
So I got my additional data to user created event by:
- hacking around `to_dict` function to pass through user model fields and my additional fields
- deleting these fields from kwargs passed to UserDatastore.user_model
- adding them back to saved user object

Which is of course ugly, but I'm further than I was a few hours ago.

**Comment by jwag956** [comment]
Interested in posting a PR to clean this up? I think this would be generally useful...

**Comment by kuba-lilz** [comment]
I would be happy to.
I'll write down my ideas on how to add it and ask for input. Should I open a new issue for it?
