### ISSUE TITLE
Feature request - custom registration validation

### ISSUE THREAD

**Issue by kuba-lilz** [jwag956/flask-security#252]
Would you be open to give users option to perform custom registration validation?

We would like to ask user for more than just email and password in registration form, and be able to validate provided values - which might include arbitrary business logic that can't be covered by simple checks available with wtforms.validatators.

I think such custom validation could be added with something along the lines of:

```python
flask_security.Security(
    application, user_datastore,
    registration_validator=custom_registration_validator)


def custom_registration_validator(register_form):

	# return nothing on success, raise wtforms.validators.ValidationError on failure
```

Whether custom_registration_validator would replace default validation (giving user option to call existing flask security registration code inside it) or be called by flask security after default validation succeeded can be discussed, I believe latter is a more fool-proof approach (probably with `additional_registration_validator` keyword then).

A simple concrete use case would be to ask user to indicate subdomain to be associated with account during registration, much like when creating a workspace in Slack - we would like to make sure that this is a valid string that isn't used by other users yet and present a nice error otherwise.

A more complex example would be requiring user to provide valid address during registration step - something that might require e.g. a call to some external service to perform validation.

This feature is important to us and if you're open to adding it we would be willing to work on its implementation.

**Comment by jwag956** [comment]
Not totally understanding - if you create your own RegistrationForm - they you have a place for your own validation logic. Just define validate(self) in your form. You can then call the origional validators if you wish. For example the SendConfirmationForm:

`    def validate(self):
        if not super(SendConfirmationForm, self).validate():
            return False
        if self.user.confirmed_at is not None:
            self.email.errors.append(get_message("ALREADY_CONFIRMED")[0])
            return False
        return True`

Why is that not sufficient?

**Comment by kuba-lilz** [comment]
Ah, silly me, overwriting validate() didn't cross my mind... My bad and thank you for your help!
