### ISSUE TITLE
Support additional permissions formats

### ISSUE THREAD

**Issue by pffs** [jwag956/flask-security#254]
Right now the permissions loader requires that the permissions attribute be a comma separated list per https://github.com/jwag956/flask-security/blob/master/flask_security/core.py#L553.

Is there any particular reason to only support this in a string format, since this function essentially just immediately changes it into a set anyway? I was thinking it could use something similar to the parsing that `add_permission` uses at https://github.com/jwag956/flask-security/blob/master/flask_security/core.py#L564, which would look something like:

```python
    def get_permissions(self):
        """
        Return set of permissions associated with role.

        .. versionadded:: 3.3.0
        """
        if hasattr(self, "permissions") and self.permissions:
            if isinstance(self.permissions, set):
                return self.permissions
            elif isinstance(self.permissions, list):
                return set(self.permissions)
            else:
                # Assume this is a comma separated list
                return set(self.permissions.split(","))
        return set([])
```

**Comment by jwag956** [comment]
I suppose there isn't a real reason - though that field is a database field - I don't know any? DBs that support 'sets' - I suppose mongodb supports lists - so that might be useful.

Do you have a usecase? certainly an easy/safe change.

**Comment by pffs** [comment]
For one of our applications, permissions is actually a table, not just a field on the role, so sqlalchemy already is returning back an iterable. Seems somewhat silly to mask the relationship and add an attribute that joins them into a string just to split them back apart again. We're migrating some stuff off Yii2 to Flask, and the Yii2 permission structure we were using is a role/permission database setup.

**Comment by jwag956** [comment]
Got it - sure - would you put a PR (be sure to add a unit test).
I would add to the comment in get_permissions to explain why it takes a list/set.

**Comment by pffs** [comment]
Will do!
