### ISSUE TITLE
Two factor

### ISSUE THREAD

**Issue by brutalsuperman** [jwag956/flask-security#262]
When I want use only google_authentificator method I get key error [here](https://github.com/jwag956/flask-security/blob/f20d336dcacd0a15151addb7e00e32625305cd94/flask_security/views.py#L720), but when sms method disabled we don`t have phone field in form, so I need rewrite form and fill default number, is it ok?

**Comment by jwag956** [comment]
Seems like it just needs a check to see if phone number in form.data before checking length

**Comment by brutalsuperman** [comment]
So will you write somenthing like .get('phone') in next relize?

**Comment by jwag956** [comment]
Yes - I think that should do it
