### ISSUE TITLE
Flask-BabelEx incompatible with latest werkzeug

### ISSUE THREAD

**Issue by ammaraskar** [jwag956/flask-security#270]
Upstream issue: https://github.com/mrjoes/flask-babelex/issues/18

```
    from flask_security import Security, SQLAlchemyUserDatastore
venv\lib\site-packages\flask_security\__init__.py:16: in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
venv\lib\site-packages\flask_security\core.py:21: in <module>
    from flask_babelex import Domain
venv\lib\site-packages\flask_babelex\__init__.py:23: in <module>
    from werkzeug import ImmutableDict
E   ImportError: cannot import name 'ImmutableDict'
```

It'd be nice to switch to `Flask-Babel` which is (slightly) more maintained, but they lack certain features we need as you've pointed out here: https://github.com/python-babel/flask-babel/pull/148#issuecomment-502188697 Can we use this issue to track maybe migrating to a different i18n plugin?

As a temporary workaround for anyone who stumbles onto this, you can pin your werkzeug to the last version with top-level exports: `werkzeug==0.16.1`

**Comment by jwag956** [comment]
Thanks for the heads-up. Looks like many folks are running around trying to patch/release old extensions - Flask-Babel has been patched.

Do you have any ideas on alternative packages? Of course this is an entire ecosystem issue - since major packages such as flask-admin also use Flask-Babelex...

**Comment by mrjoes** [comment]
The Flask-BabelEx fix was merged and a new version was released.

**Comment by jwag956** [comment]
The latest babelex fixes this. There is ongoing discussion around backporting to babel - outside scope of this issue (but would be great!)
