### ISSUE TITLE
Data is not transferred to the additional field through the JSON API

### ISSUE THREAD

**Issue by dustyattic** [jwag956/flask-security#271]
I added the "**username**" field to the "user" table.

Everything works if I execute the code:

```
@ app.before_first_request
def create_user ():
     db.create_all ()
     user_datastore.create_user (username = "test", email = "test@me.com", password = hash_password ("password"))
     db.session.commit ()
```

This is also the case if I add data through a form, as described in the Customizing manual.

When trying to transfer data through Postman as JSON:
```
{
    "username": "test1",
    "email": "test1@me.com",
    "password": "SecretPassword"
}
```

only "email" and "password" are transferred to the "user" table, but the "username" field is ignored.

Tell me, what am I doing wrong?

**Comment by jwag956** [comment]
The JSON API is really just an alternate input style for the same form. So make sure you customize your form (I assume this is register form?) then try JSON. The (probably not documented) subtlety is that JSON ALWAYS uses the confirm_register_form (same as if you have confirmable enabled) - so make sure you extended that to add username.
