### ISSUE TITLE
Allow SameSite='None' to be set explicitly on cookies

### ISSUE THREAD

**Issue by drericrobinson** [jwag956/flask-security#285]
With changes in Chromium to the samesite cookie, sites need the ability to set `SameSite='None'` explicitly, rather than merely `Lax` or `Strict`.

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Chrome used to default to `None` if no value was set, but in some of the latest experiments in Chrome 80 it defaults to `Lax`. This can prevent cookies from being able to be set for sites running in iframes on third-party sites.

**Comment by jwag956** [comment]
Thanks for the issue. You don't say WHICH cookie you are concerned with.
As of Werkzeug 1.0 (which is what flask and flask_security use to set cookies), it accepts the
string "None" for samesite.
Flask, which owns the session cookie has a config setting: SESSION_COOKIE_SAMESITE which you could set to "None" (note - it's a string, not python None).

Flask-Security-Too has a CSRF cookie - which takes SECURITY_CSRF_COOKIE which can set any cookie parameter.

That leaves the REMEMBER_COOKIE - which is managed by Flask-Login - and that apparently does NOT have any way to set samesite.

**Comment by drericrobinson** [comment]
Awesome, thanks for the quick response.

**Comment by rengaboy** [comment]
> 
@jwag956

**Hello everyone!**
**Chris, thank you for maintaining this awesome repo.**

At July 29, 2021, there was commit in Flask-Login repo, which added options to REMEMBER_COOKIE variable. One of them is "REMEMBER_COOKIE_SAMESITE", which is None by default, but allows to set cookie to Lax. Is it posiible to add an opportunity to pass this option from Flask-Security to Flask-Login? full list of configurable variables here - [Flask-Login remember me](https://flask-login.readthedocs.io/en/latest/#remember-me)
