### ISSUE TITLE
Support Bearer tokens

### ISSUE THREAD

**Issue by alejom99** [jwag956/flask-security#286]
Hello, when using token authentication, it's very common for the header to be `Authorization: Bearer xxxx`. Right now, the `SECURITY_TOKEN_AUTHENTICATION_HEADER` configuration parameter allows for setting the header to be `Authorization`, but the problem is that the value cannot be `Bearer xxxx`, it can only be `xxxx`. So, I was wondering if it's possible to support Bearer tokens. All that needs to be done is change [this line](https://github.com/jwag956/flask-security/blob/dec654dc171a06f5600944d669ee17d52d9c5f9b/flask_security/core.py#L459)

```
token = request.args.get(args_key, header_token)
```

to

```
token = request.args.get(args_key, header_token)
token = token.replace("Bearer ", "")
```

I can submit a PR if you agree. 

Thanks.

**Comment by jwag956** [comment]
I am not sure that is a good idea. Check out:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
Authentication Schemes - 'Bearer'  implies oauth2 - which these aren't.
If/when Flask-Security implements an oauth server - we would want to be able to differentiate those from today's Flask-Security tokens.

**Comment by alejom99** [comment]
Understood, thanks.
