### ISSUE TITLE
Problem customizing registration form following documentation

### ISSUE THREAD

**Issue by mvfpoa** [jwag956/flask-security#294]
I tried to simply customize registration form without success. 

So I decided to copy the documentation examples to see what I could be doing wrong, but even following documentation I am unable to customize registration form.

Can someone help me? or is this a bug?

The following snippet should have rendered a fourth field labeled 'Name' to my registration form, shouldn't it?

```python
from flask import Flask, render_template_string
from flask_security import Security, auth_required, current_user, SQLAlchemyUserDatastore, hash_password
from flask_security.models import fsqla
from flask_security.forms import RegisterForm
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from wtforms import StringField

app = Flask(__name__)
app.config['SECRET_KEY'] = 'pf9Wkove4IKEAXvy-cQkeDPhv9Cb3Ag-wyJILbq_dFw'
app.config['SECURITY_PASSWORD_SALT'] = '146585145368132386173505678016728509634'
app.config['SECURITY_PASSWORD_HASH'] = 'plaintext'
app.config['SECURITY_TRACKABLE'] = False
app.config['SECURITY_CONFIRMABLE'] = False
app.config['SECURITY_REGISTERABLE'] = True
app.config['SECURITY_RECOVERABLE'] = True
app.config['SECURITY_PASSWORDLESS'] = False

db = SQLAlchemy(app)

fsqla.FsModels.set_db_info(db)
class User(db.Model, fsqla.FsUserMixin):
    name = db.Column(db.String)

class Role(db.Model, fsqla.FsRoleMixin):
    pass

class ExtendedRegForm(RegisterForm):
    name = StringField("Name: ")

ds = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, ds, register_form=ExtendedRegForm)

csrf = CSRFProtect(app)

@app.before_first_request
def init_db():
    db.create_all()
    testrole = ds.create_role(name="testrole", description='')
    a = ds.create_user(email="a@b.co", password=hash_password('123'))
    ds.add_role_to_user(a, testrole)
    ds.commit()

@app.route('/plataform/')
@auth_required()
def main():
    return render_template_string('{{username}}', **dict(username=current_user.email))

if __name__ == "__main__":
    app.run()
```
freeze content (edited):
```
Flask==1.1.1
Flask-Security-Too==3.3.3
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.3
WTForms==2.2.1
```

**Comment by jwag956** [comment]
It doesn't look like you changed the template - there is nothing magic going on here - you correctly added the new field to your DB model, and added it to the form - but you ALSO have to actually change the template that renders the form.

**Comment by mvfpoa** [comment]
ok... that was dumb. I have little understanding of wtf, and reading the documentation made me feel that pointing to custom class would render it like the class itself.
Does it worth to upgrade documentation to have it more clearer?
May I suggest changing it a little bit (https://flask-security-too.readthedocs.io/en/stable/customizing.html#forms)?

> All forms can be overridden. For each form used, you can specify a replacement class. This allows you to add extra fields to match your custom view or to override existing validators, e.g. the register form:
