### ISSUE TITLE
Enabling Flask Security causes all requests to load significantly slower

### ISSUE THREAD

**Issue by rushilsrivastava** [jwag956/flask-security#297]
We have recently started using `flask-security-too` in our codebase, and we integrated it similar to the example given [here](https://flask-security-too.readthedocs.io/en/stable/quickstart.html#id4). However, upon integrating `flask-security-too`, we noticed that general requests (route, static files, etc.) in development have become significantly slower (1000% slower with images). We have not experimented with any authentication yet.

**Loading time with `Flask-Security-Too`**
![image](https://user-images.githubusercontent.com/11495473/79124981-3cdb0b80-7d52-11ea-90ff-d5c9b956e89d.png)

**Loading time without `Flask-Security-Too`**
![image](https://user-images.githubusercontent.com/11495473/79125018-4b292780-7d52-11ea-872d-181fe739c8cc.png)

Here are some relevant codebits:
**Register Function:**
```
def register_security(app):
    """Register Flask-Security-Too"""
    user_datastore = SQLAlchemyUserDatastore(db, dashboard.models.User, dashboard.models.Role)
    security.init_app(app, user_datastore)
    return None
```
**Models:**
```
class RolesUsers(SurrogatePK, Model):
    __tablename__ = 'roles_users'
    user_id = Column('user_id', db.Integer(), db.ForeignKey('users.id'))
    role_id = Column('role_id', db.Integer(), db.ForeignKey('roles.id'))


class Role(RoleMixin, SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True)
    description = Column(db.String(255))


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = "users"
    email = Column(db.String(255), unique=True, nullable=False)
    #: Randomly generated uuid
    uuid = Column(db.String(32), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.LargeBinary(255), nullable=False)
    last_login_at = Column(db.DateTime())
    current_login_at = Column(db.DateTime())
    last_login_ip = Column(db.String(100))
    current_login_ip = Column(db.String(100))
    login_count = Column(db.Integer())
    active = Column(db.Boolean(), nullable=False, default=False)
    fs_uniquifier = Column(db.String(255))
    confirmed_at = Column(db.DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('users', lazy='dynamic'))
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    verified = Column(db.Boolean(), nullable=False, default=False)
```

This is all we have done with the library so far, and we were able to narrow it down to this library by commenting out the `register_security()` function and testing. We would love to use `flask-security-too`, is there a reason we are facing this issue?

**Comment by jwag956** [comment]
Could be a bunch of things - however lets start with how you are making the requests. Are you sending the session cookie? Are you sending any authentication headers?

One thing in your above stats - you are transferring 1/3 more data with flask security on - which is odd unless it is actually returning something (which it shouldnt).
So - it would help to see more code - is this a public repo? if not - seeing your requests and your API endpoint would be useful.

**Comment by rushilsrivastava** [comment]
> Are you sending the session cookie? Are you sending any authentication headers?

Nothing, we have a very basic route setup.
```
@blueprint.route("/", methods=["GET"])
def index():
    """Home page."""
    return render_template("public/index.html")
```

We really only setup the SQLAlchemy Models and registered flask security. We didn't add any other features because we noticed the increase in load times.

> is this a public repo? if not - seeing your requests and your API endpoint would be useful.
Unfortunately, the repo isn't public but I can share any other code pieces needed. We found it really strange because we hadn't even added the flask security features in yet.

If it helps, here is our database module:
```
from .extensions import db

# Alias common SQLAlchemy names
Column = db.Column
relationship = db.relationship
basestring = (str, bytes)

class CRUDMixin(object):
    """Mixin that adds convenience methods for CRUD (create, read, update, delete) operations."""

    @classmethod
    def create(cls, **kwargs):
        """Create a new record and save it the database."""
        instance = cls(**kwargs)
        return instance.save()

    def update(self, commit=True, **kwargs):
        """Update specific fields of a record."""
        for attr, value in kwargs.items():
            setattr(self, attr, value)
        return commit and self.save() or self

    def save(self, commit=True):
        """Save the record."""
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

    def delete(self, commit=True):
        """Remove the record from the database."""
        db.session.delete(self)
        return commit and db.session.commit()


class Model(CRUDMixin, db.Model):
    """Base model class that includes CRUD convenience methods."""

    __abstract__ = True


# From Mike Bayer's "Building the app" talk
# https://speakerdeck.com/zzzeek/building-the-app
class SurrogatePK(object):
    """A mixin that adds a surrogate integer 'primary key' column named ``id`` to any declarative-mapped class."""

    __table_args__ = {"extend_existing": True}

    id = Column(db.Integer, primary_key=True)

    @classmethod
    def get_by_id(cls, record_id):
        """Get record by ID."""
        if any(
            (
                isinstance(record_id, basestring) and record_id.isdigit(),
                isinstance(record_id, (int, float)),
            )
        ):
            return cls.query.get(int(record_id))
        return None


def reference_col(tablename, nullable=False, pk_name="id", foreign_key_kwargs=None, column_kwargs=None):
    """Column that adds primary key foreign key reference.

    Usage: ::

        category_id = reference_col('category')
        category = relationship('Category', backref='categories')
    """
    foreign_key_kwargs = foreign_key_kwargs or {}
    column_kwargs = column_kwargs or {}

    return Column(
        db.ForeignKey(f"{tablename}.{pk_name}", **foreign_key_kwargs),
        nullable=nullable,
        **column_kwargs,
    )
```

**Comment by jwag956** [comment]
Ok - you shouldn't even be getting any DB calls yet unless something is really odd. Can you share your client test code (the thing making requests and measuring response?)

**Comment by rushilsrivastava** [comment]
These pictures give a more detailed comparison.

**With `flask-security-too`:**
![image](https://i.imgur.com/UrwUA2a.png)

**Without `flask-security-too`:**
![image](https://i.imgur.com/q3ZKpuT.png)

**Comment by jwag956** [comment]
I assume no console messages (exceptions) either for your server (is that running in  container? can you see console log?), and no console messages on chrome?

From that chart - that looks like the old behavior of authentication token (prior to the fs_uniquefier field). Are you sure you are using Flask-Security-Too and not Flask-Security?

I'll try to set up a test for anonymous access to see if I can find anything.

In the meantime -if you'd be willing - actually enabling authentication and logging in and using the session cookie - I think you'll find it adds no overhead. (You probably want to turn off CSRF - set WTF_CSRF_ENABLED = False).

**Comment by jwag956** [comment]
Oh - and I assume you have set a SECURITY_PASSWORD_SALT? Could you provide all your SECURITY_xxx settings?

**Comment by rushilsrivastava** [comment]
> I assume no console messages (exceptions) either for your server (is that running in container? can you see console log?), and no console messages on chrome?

Yup, no errors on chrome console or the flask console. 

> Are you sure you are using Flask-Security-Too and not Flask-Security?

Yes, we are on `flask-security-too==3.4.0`

> actually enabling authentication and logging in and using the session cookie

Will definitely take a look into this and will report back here.

> Oh - and I assume you have set a SECURITY_PASSWORD_SALT? Could you provide all your SECURITY_xxx settings?

Yes, we have `SECURITY_PASSWORD_SALT` defined, and that is the only SECURITY_xxx setting we have.
```SECURITY_PASSWORD_SALT=salt```

**Comment by jwag956** [comment]
Thanks - had to ask :-)

Can you send a screen shot of request and response headers for one of the requests? I am curious that you are getting 304 Not Modified responses - I didn't think Flask did that out of the box (ahh - cookiecutter does that - and it also has authentication via Flask-Login). I'll have to setup a cookiecutter to try and reproduce.

**Comment by rushilsrivastava** [comment]
Interestingly, there seems to be a session cookie.
**Enabled:**
![image](https://user-images.githubusercontent.com/11495473/79135890-e9be8400-7d64-11ea-8fac-a0e48427f8e4.png)

**Disabled:**
![image](https://user-images.githubusercontent.com/11495473/79135990-16729b80-7d65-11ea-839a-83bb412d0b23.png)

**Comment by rushilsrivastava** [comment]
Also, I believe the 304 status code is for caching, I believe it comes via `flask-caching` (not confirmed).

**Comment by jwag956** [comment]
Yes - looks like cookiecutter-flask configures Flask-Login - just as Flask-Security does - not sure in what sequence or with which key. This will take some exploring.

**Comment by jwag956** [comment]
I have cookie cutter up and running with FS. The first thing I noticed is that cookiecutter (CC) defines its own User/Role models, and also initializes many things that FS also initializes.
For example, the CLI (shellcontext) uses their db and user model - and from your code snippet - it looks like you defined your OWN User/Role models in their own files. Are you sure that your DB User model actually contains the fs_uniquifier field?
In general though - I think this issue likely is that there are 2 competing security models going on.

I would disable cookiecutters auth stuff - CSRF, bcrypt, login_manager; make sure that your DB actually contains YOUR user model columns.

Also - where are you calling register_security? is it before or after things like login_manager.init_app(app)???

**Comment by rushilsrivastava** [comment]
> cookiecutter (CC) defines its own User/Role models, and also initializes many things that FS also initializes.

Yup! We based off our structure from CC, but we decided not to adopt their `models.py`. Our User/Role/RolesUsers is based off the FS example.

> Are you sure that your DB User model actually contains the fs_uniquifier field?

Yes, here is a screenshot from DataGrip. The only difference we made is that we elected to make the name of the tables `Users` and `Roles` for consistency.
![image](https://user-images.githubusercontent.com/11495473/79177653-38493e00-7db8-11ea-9bbf-f27b81d9ea6b.png)

> I would disable cookiecutters auth stuff - bcrypt, login_manager; make sure that your DB actually contains YOUR user model columns.

I went ahead and commented out all of these features but am seeing the same performance. Here is my `register_extensions()` now.
```
def register_extensions(app):
    """Register Flask extensions."""
    # bcrypt.init_app(app)
    db.init_app(app)
    # csrf_protect.init_app(app)
    # login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    cache.init_app(app)
    flask_static_digest.init_app(app)
    mail.init_app(app)
    celery_ext.init_app(app)
    return None
```

> Also - where are you calling register_security? is it before or after things like login_manager.init_app(app)???

I am calling `register_security()` right after `register_extensions()` as it needs access to SQLAlchemy.

**Comment by jwag956** [comment]
Thanks for the update - will have to pursue this more tomorrow...

Do you actually have any users defined? can you dump a record?

**Comment by rushilsrivastava** [comment]
I don't have any users defined at the moment, but I will look into setting up the login and register via FS. I did a more detailed analysis with Chrome Developer Tools, and it looks like the main thing affected is the TTFB, which leads me to believe that there is some overhead that is causing a hold up on each request. The content download speed remains the same. This is when the user is not authenticated, it will be interesting to see what happens when the user is authenticated.

**Comment by rushilsrivastava** [comment]
**Update:** I cleared the data for the website (cookies, application data, etc.) and everything works now! 

Here is my guess on why this is happening: The session token that I shared before was previously generated by Flask-Login (when we were using that library). This may have caused problems with session verification with Flask-Security. When the session token was regenerated, this fixed the problem.

I wonder if this is intentional behavior, shouldn't the session token be regenerated if invalid?

**Comment by jwag956** [comment]
Thanks for the update.Not really clear what was going on - Flask-Login generates the session cookie when necessary. I don't know if there was an issue that 2 different user_loaders were being called or different user id in the session cookie. But glad things are working now.

**Comment by rushilsrivastava** [comment]
Appreciate your help! Thanks for the prompt replies and looking into this!
