### ISSUE TITLE
Is it possible to flash errors appended to the form fields?

### ISSUE THREAD

**Issue by rushilsrivastava** [jwag956/flask-security#299]
The current logic in FS appends the errors to each field using WTForms. We use a method in our views to render all the errors through flashes:

```
def flash_errors(form, category="warning"):
    """Flash all errors for a form."""
    for field, errors in form.errors.items():
        for error in errors:
            flash(error, category)
```

Ideally, we would like to use a similar approach while rendering all the templates via FS. Because we have to call `flash_errors` from view, there doesn't seem to be a way to do this. Currently, I am just creating my own view and passing in the login form, but I don't think this is the right approach:
```
@blueprint.route("/login/", methods=["GET", "POST"])
def login():
    """Login existing user."""
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == "POST":
        if form.validate_on_submit():
            login_user(form.user)
            redirect_url = request.args.get("next") or url_for("dashboard.index")
            return redirect(redirect_url)
        flash_errors(form, "error")
    return render_template("security/login_user.html", login_user_form=form)
```
The problem with this is, there is no way to disable the default FS login route, like there is with register, recover, etc. I also like being able to use this approach as it allows me to make use of `next` to redirect to the the post login url I desire. Is there a better way to tackle this problem so that I can flash the errors, while also being able to retain functionality of the `next` parameter?

**Comment by jwag956** [comment]
Without getting into a UX discussion - I don't think flashing is really the right way to go - the way FS uses it is when a redirect happens due to a successful action. Actual errors in form submission is nicely displayed next to the element in error - a nice UX I think. flashes disappear on next request.
So no - that's not how FS is structured.

I don't totally  understand your 'next' question - you can set the SECURITY_POST_LOGIN_VIEW config to have it redirect to where you want - also - all views in FS will honor the ?next=xxx parameter.

**Comment by rushilsrivastava** [comment]
Understood, thanks!

**Comment by rushilsrivastava** [comment]
@jwag956 I have tested this more in depth, and I have found that certain features don't quite work when passing in custom forms. Please see my example below:

```
class BootstrapVerifyEmail(EmailInput):
    def __init__(self, error_class=u'is-invalid'):
        super(BootstrapVerifyEmail, self).__init__()
        self.error_class = error_class

    def __call__(self, field, **kwargs):
        print(field.data)
        if field.type is EmailField:
            kwargs['type'] = "email"
        if field.errors:
            c = kwargs.pop('class', '') or kwargs.pop('class_', '')
            kwargs['class'] = u'%s %s' % (self.error_class, c)
        return super(BootstrapVerifyEmail, self).__call__(field, **kwargs)


class BootstrapVerifyPassword(PasswordInput):
    def __init__(self, error_class=u'is-invalid'):
        super(BootstrapVerifyPassword, self).__init__()
        self.error_class = error_class

    def __call__(self, field, **kwargs):
        if field.errors:
            c = kwargs.pop('class', '') or kwargs.pop('class_', '')
            kwargs['class'] = u'%s %s' % (self.error_class, c)
        return super(BootstrapVerifyPassword, self).__call__(field, **kwargs)

class ExtendedLoginForm(LoginForm):
    """Login form."""
    email = StringField("Email", validators=[DataRequired()], widget=BootstrapVerifyEmail())
    password = PasswordField("Password", validators=[DataRequired()], widget=BootstrapVerifyPassword())
    remember = BooleanField("Remember me")

    user_datastore = SQLAlchemyUserDatastore(
        db, dashboard.models.User, dashboard.models.Role
    )
    security_ctx = security.init_app(app, user_datastore, login_form=ExtendedLoginForm)
```

Using this code, the `next` parameter is never redirected too. However, as soon as I remove the custom `login_form`, it redirects me to the `next` parameter.

I also found something similar with register:

```
class ExtendedRegisterForm(ConfirmRegisterForm):
    """Register form."""
    email = EmailField("Email Address", validators=[DataRequired(), Email(), Length(min=6, max=40)], widget=BootstrapVerifyEmail())
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=40)], widget=BootstrapVerifyPassword())
    password_confirm = PasswordField("Confirm password", [DataRequired(), EqualTo("password", message="Passwords must match!")], widget=BootstrapVerifyPassword())

    terms_conditions = BooleanField("I agree to the Terms and Conditions", validators=[DataRequired()], widget=BootstrapVerifyBoolean())
    privacy_policy = BooleanField("I agree to the Privacy Policy", validators=[DataRequired()], widget=BootstrapVerifyBoolean())

    recaptcha = RecaptchaField("reCAPTCHA", validators=[Recaptcha(message="Please fill out the reCAPTCHA!")])
```

When using this Extended Form, the email field is never checked for duplicity and the server throws an error as the email already exists in the DB. However, when I remove the Extended Form, FS renders a proper error saying that the email already exists.

Am I setting this up incorrectly?

**Comment by jwag956** [comment]
Not totally sure - but I would start by adding a validation method:

    def validate(self):
        if not super().validate():
            return False
       # do any additional validation you want
      return True.

As to why 'next' isn't working - not sure...

**Comment by rushilsrivastava** [comment]
I followed the documentation from [here](https://flask-security-too.readthedocs.io/en/stable/customizing.html#forms), I don't think it needs to have the validate function, but what I was missing were the Mixins that FS creates. After importing them into my form, I got it to work!

```
class ExtendedLoginForm(LoginForm, NextFormMixin):
    """Login form."""
    email = StringField("Email", validators=[DataRequired()], widget=BootstrapVerifyEmail())
    password = PasswordField("Password", validators=[DataRequired()], widget=BootstrapVerifyPassword())
    remember = BooleanField("Remember me")


class ExtendedRegisterForm(ConfirmRegisterForm):
    """Register form."""
    email = EmailField("Email Address", validators=[DataRequired(), email_validator, Length(min=6, max=40), email_required, unique_user_email], widget=BootstrapVerifyEmail())
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=40)], widget=BootstrapVerifyPassword())
    password_confirm = PasswordField("Confirm password", [DataRequired(), EqualTo("password", message="Passwords must match!")], widget=BootstrapVerifyPassword())

    terms_conditions = BooleanField("I agree to the Terms and Conditions", validators=[DataRequired()], widget=BootstrapVerifyBoolean())
    privacy_policy = BooleanField("I agree to the Privacy Policy", validators=[DataRequired()], widget=BootstrapVerifyBoolean())

    recaptcha = RecaptchaField("reCAPTCHA", validators=[Recaptcha(message="Please fill out the reCAPTCHA!")])
```
