### ISSUE TITLE
Black Formatting

### ISSUE THREAD

**Issue by baurt** [jwag956/flask-security#87]
Now that this package is starting to go more towards a black style, would you be opposed to blackening the entire package?  There is a plugin for pytest to use black formatting: https://github.com/shopkeep/pytest-black.  This doesn't work with Python 2, which would mean that the Python 2 support would have to be dropped.  Not sure your feelings about that since Python 2 is not going to be supported as of 1/1/2020 (https://pythonclock.org/).

**Comment by jwag956** [comment]
I just was introduced to Black - I like it. My thinking right now is that Flask-Security, being part of the flask eco-system should not be more restrictive than Flask - that is what drives my updating of package versions etc.
I have not looked closely at pytest-black - as long as the RUNTIME and CI continue to work on python 2.7 - I see no reason that development shouldn't require Python 3 (don't know if that is possible).

As soon as flask (and other pallets projects) drop 2.7 - I will the next day!

**Comment by baurt** [comment]
Just found out that pytest-black just released 0.3.7, which allows use of the --black pytest tag for Python 2.7 and Python 3. I'll look into this.
