### ISSUE TITLE
cache system for apikey not working

### ISSUE THREAD

**Issue by eregnier** [jwag956/flask-security#91]
Hello @jwag956 ,

the newly added feature of caching apikeys seems to not work in your fork.
Only the Default Flask security dict is used and configuration from my project's config.py file is not used as Flask-Security does.

I don't know what are the differences between the two projects on this topic but I cannot execute the code of my PR as the option to use cache is not set properly.

**Comment by jwag956** [comment]
Hmm - thats no good!
can you point me to your config.py

**Comment by eregnier** [comment]
Unfortunatly, it is a private repository. but it looks like :

```python
from dotenv import load_dotenv
from os.path import abspath, dirname, join
import os
import logging

load_dotenv(join(abspath(dirname(__file__)), ".env"))
get = os.environ.get
envtype = get("ENVTYPE", "default")

class Config:
    # stuff
    USE_VERIFY_PASSWORD_CACHE = True
    # other stuff

class <other>Config(Config):
    # values overrides
    pass

configs = {
    "production": ProductionConfig,
    "development": DevelopmentConfig,
    "qualification": QualificationConfig,
    "testing": TestingConfig,
    "default": DevelopmentConfig,
}

```

**Comment by jwag956** [comment]
Not sure - I assume you forked and ran against the develop branch and not master?
There was a PR in develop and I picked up that tried to fix how apps get initialized.
So - can you show me how you are initializing your flask app?

**Comment by eregnier** [comment]
The setup is done thanks to my lib https://github.com/eregnier/Flask_AuthOOB that is a Flask extention to setup authentication using flask security with as few setup as possible.
So the setup code is in this library, I did not changed it in-between, exept I updated the flask-security dependency here : https://github.com/eregnier/Flask_AuthOOB/blob/master/setup.py#L29

**Comment by jwag956** [comment]
ok - I will look into it - but I need to know - when you say it worked against Flask-Security - was that against the master branch or develop branch?

This is the PR i am wondering about - it is in my fork and in develop - but not in 3.0.0
https://github.com/mattupstate/flask-security/pull/703

**Comment by eregnier** [comment]
It is against the master branch as I installed the flask-security dependency with a simple line in setup.py "flask-security", so it was the latest master release. However, I did the PR from develop on the upstream flask-security project on my workstation (the version I setuped with `python setup.py install -e`).

Hopping this helps.

Thank you for your time again :) .

**Comment by jwag956** [comment]
ok - so I am still missing where you are actually configuring - such as app.config.from_object() etc.

so I think there is a piece still missing!

**Comment by eregnier** [comment]
I have a quite simple setup for my flask app. the application.py file is :
```python
from config import configs, envtype
from app import create_app, app, db

from app.apidoc import register_api_doc

@app.teardown_appcontext
def shutdown_session(exception=None):
    db.session.remove()


app.config.from_object(configs[envtype])
create_app(app, db)
register_api_doc(app)
```

and the app/__init__.py file is made of 2 parts : 
1) imports and init of some modules
2) the create app "callback" once conf is loaded
```python
import logging
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_marshmallow import Marshmallow
from flask_mail import Mail
from flask_authoob import AuthOOB
from app.utils import SendGridEmailProvider
import googlemaps

app = Flask(__name__)
db = SQLAlchemy()
Migrate(app=app, db=db)
login_manager = LoginManager(app)
ma = Marshmallow()
migrate = Migrate(app, db)
mail = Mail()
authoob = AuthOOB()
tools = {}

#some flask hooks

def create_app(app, db):
       
    from app.models.user import CustomUserMixin, CustomUserSchemaMixin, CustomHooks

    authoob.init_app(
        app,
        db,
        CustomUserMixin=CustomUserMixin,
        CustomUserSchemaMixin=CustomUserSchemaMixin,
        custom_hooks=CustomHooks(),
    )

    @app.shell_context_processor
    def make_shell_context():
        return dict(app=app, db=db, User=authoob.User)

    # and so on for many more plugin setup
```

**Comment by jwag956** [comment]
Hmm - I think this is because you don't have SECURITY_USE_VERIFY_PASSWORD_CACHE - all Flask-Security arguments need to be prefixed with 'SECURITY_'.
Your PR actually had the configuration as part of the Flask config, not the Security config. My minor changes:
https://github.com/jwag956/flask-security/pull/80/commits/5c0d628c4fc6e9b9d7389ff6bf08fd15f55b0fd1

changed that so they are consistent with all the other configuration variables.

**Comment by eregnier** [comment]
Yes, indeed that was it.
Thank you for your help. I did not noticed this until now.
